version: '3'
services:
    app:
        build: .
        env_file:
            - .env
        ports:
            - "8080:8080"
        container_name: mvj-ui
        platform: linux/amd64

networks:
    default:
        external:
            name: tunnistamo_net
